// Type Imports
import type { PropertiesType } from '@/types/apps/propertyTypes'

export const db: PropertiesType[] = [
  {
    id: 1,
    type: 'local',
    code: '3457567',
    quality: 'bueno',
    adviser: 'Pedro Pérez',
    status: 'inactivo',

    name: "Esteban Gómez",
    cellphone: "300234533",
    email: "e@gmail.com",
    authorization: "si",

    department: 'Antioquia',
    city: 'Medellín',
    neighborhood: 'La floresta',
    coownershipname: 'Los Soles',
    propertytype: 'Vivienda',
    charge: 'Arriendo',
    canyon: '25.000.000',
    salevalue: '50.000.000',
    adminvalue: '100.000',
    adminincluded: 'si',
    builtarea: '50',
    privatearea: '49',
    yearconstruction: '10-04-1987',
    addressbuild: 'Cll.  47a # 83 - 27',

    coveredfinishes: ["Teja eternit", "Teja de barro"],
    heightmeters: "3",
    depthmeters: "4",
    frontmeters: "2",
    kitchen: ["concineta", "Gas natural"],
    propertystatus: ["Bueno", "En construcción"],
    energy: ["Monofásica", "Trifásica"],
    others: "Cableado de red",
    winery: "Liviana",
    floors: ["Adoquín", "Laminado"],
    balcony: "no",
    terrace: "si",
    airconditioning: "si",
    centralair: "no",
    surveillance: ["Portería vigilancia", "Vigilancia 24x7"],
    bathroomnum: '2',
    garagenum: '1',

    industrialpark: 'si',
    parkingbay: 'no',
    communalbathrooms: 'no',
    publictoilets: 'si',
    leveldock: 'si',
    depresseddock: 'no',
    loadingcapacity: 'si',
    bridgecrane: 'si',
    usefulroom: 'si',
    digitalaccess: 'no',
    facade: ['Anterjardín', 'Cemento'],
    amouncapacity: '2',
    numberlevels: '3',
    onfloor: '1',
    otherspecifications: {
      quantityfire: "1",
      quantityrural: "3"
    },
    parking: 'Comunal',
    unit: 'Abierto',
    specificationsAmount: '',
    commonzones: ['Auditorio', 'Piscina'],

    surroundings: ["Colegios", "Universidades"],
    landmarks: "Bomba de gasolina",
    observations: "Colegio",
    collector: "Pedro Jaime",
    collectionmedium: "3008645218",
    collectiodate: "21-05-2023",
  },
  {
    id: 2,
    type: 'vivienda',
    code: '4523891',
    quality: 'excelente',
    adviser: 'Carla Rodríguez',
    status: 'publicado',

    name: "Laura Torres",
    cellphone: "3109876543",
    email: "laura.t@gmail.com",
    authorization: "si",

    department: 'Cundinamarca',
    city: 'Bogotá',
    neighborhood: 'Chapinero',
    coownershipname: 'Torre Empresarial',
    propertytype: 'Comercio',
    destination: '',
    charge: 'Venta',
    canyon: '40.000.000',
    salevalue: '100.000.000',
    adminvalue: '150.000',
    adminincluded: 'no',
    builtarea: '80',
    privatearea: '75',
    yearconstruction: '15-08-2010',
    stratum: '',
    addressbuild: 'Cra. 13 # 45-67',

    coveredfinishes: ["Teja eternit", "Teja de barro"],
    propertystatus: ["Bueno", "En construcción"],
    roomsnum: '4',
    bathroomnum: '2',
    garagenum: '1',
    closet: "si",
    closetcount: '4',
    linencloset: "no",
    linenclosetcount: "",
    dressingroom: "si",
    dressingroomcount: "2",
    bathtub: "si",
    jacuzzi: "no",
    chimney: "no",
    kitchen: ["concineta", "Gas natural"],
    floors: ["Adoquín", "Laminado"],
    dining: "si",
    diningroom: "no",
    lounge: "si",
    deck: "no",
    balcony: "si",
    terrace: "no",
    hall: "si",
    clotheszone: "no",
    yard: "si",
    duplex: "no",
    loft: "si",
    penthouse: "no",
    securitydoor: "si",


    usefulroom: 'si',
    exposedbrick: 'no',
    numberlevels: '2',
    onfloor: '2',
    otherspecifications: {
      quantityfire: "1",
      quantityrural: "3"
    },
    specificationsAmount: '',
    parking: 'Cubierto',
    surveillance: ['Portería vigilancia', 'Vigilancia 24x7'],
    commonzones: ['Auditorio', 'Piscina'],
    loadingcapacity: 'si',
    loadingcapacitycount: '2',



    surroundings: ["Colegios", "Universidades"],
    landmarks: "Centro comercial cercano",
    observations: "Ubicación privilegiada en zona empresarial",
    collector: "Luis Sánchez",
    collectionmedium: "3107654321",
    collectiodate: "05-09-2023",

  }


]



