export interface formDataInterface {
    id?: number
    owner_id?: number
    globaltype?: string
    name?: string
    cellphone?: string
    owner_identification?: string
    owner_email?: string
    type_contact?: string[]
    authorizes_publishing?: string
    department?: string
    city?: string
    neighborhood?: string
    coownershipname?: string
    property_type?: string
    destination_property?: string
    charge?: string
    canyon?: number
    sale_value?: number
    valuesArrayAddress?: string[]
    administration_value?: number
    include_administration?: string
    dressingroomcount?: number
    built_area?: number
    linenclosetcount?: number
    private_area?: number
    status_complete: boolean
    year_of_construction?: string
    stratum?: number
    address?: string
    coveredfinishes?: string[]
    height?: number
    depth?: number
    front?: number
    type_kitchen?: string[]
    propertystatus?: string
    electric_connection?: string[]
    others?: string[]
    winery?: string
    type_floor?: string[]
    has_a_balcony?: string
    has_a_terrace?: string
    has_air_conditioner?: string
    has_central_air?: string
    surveillance?: string[]
    number_of_bathrooms?: number
    number_of_parking_spaces?: number
    bathtub?: string
    jacuzzi?: string
    chimney?: string
    closet?: string
    linencloset?: string
    dressingroom?: string
    dining?: string
    diningroom?: string
    penthouse?: string
    yard?: string
    clotheszone?: string
    hall?: string
    lounge?: string
    deck?: string
    duplex?: string
    loft?: string
    securitydoor?: string
    number_of_rooms?: number
    useful_room?: string
    exposedbrick?: string
    number_of_levels?: number
    floor_number?: number
    otherspecifications?: string[]
    combinedSpecifications?: { specification: string; amount: number }[];
    specificationsWithAmounts?: {}
    specificationsAmount?: { [key: string]: number }
    parking_lot?: string
    surveillanceExternal?: string[]
    commonzones?: string[]
    industrial_park?: string
    parking_bay?: string
    communal_bathrooms?: string
    public_toilets?: string
    level_dock?: string
    idepressed_dock?: string
    floor_load_capacity?: string
    bridgecrane?: string
    digital_access_in_building?: string
    facade?: string[]
    quantity_load_capacity?: number
    unit_type?: string
    otherspecificationsDings?: string[]
    landmarks?: string
    observations?: string
    collector_name?: string
    collection_medium?: string
    collection_date?: string
    closetcount?: string
    publication_status?: string
}
